apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: redis
data:
  redis.conf: |
    bind 0.0.0.0
    protected-mode no
    requirepass "yourpassword"
    maxmemory 1gb
    maxmemory-policy allkeys-lru